In [1]:
#Pandas DataFrames
import pandas as pd
import numpy as np
import scipy.stats as st

In [3]:
data=np.array([6,7,7,12,13,13,15,16,19,22])
st.zscore(data)

array([-1.39443338, -1.19522861, -1.19522861, -0.19920477,  0.        ,
        0.        ,  0.39840954,  0.5976143 ,  1.19522861,  1.79284291])

In [4]:
data1=np.array([[5,6,7,7,8],
              [8,8,8,9,8],
              [2,2,4,4,5]])

In [5]:
st.zscore(data1)

array([[ 0.        ,  0.26726124,  0.39223227,  0.16222142,  0.70710678],
       [ 1.22474487,  1.06904497,  0.98058068,  1.13554995,  0.70710678],
       [-1.22474487, -1.33630621, -1.37281295, -1.29777137, -1.41421356]])

In [6]:
cardio=pd.read_csv("Cardio_vascular.csv")
cardio.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [10]:
cardio1=cardio.copy()
cardio1.head()
cardio1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [11]:
cardio2=st.zscore(cardio1)

In [12]:
cardio2

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,-0.268674,0.661504,-0.915755,-0.377636,-0.659332,-0.418878,0.891255,0.820689,-0.712287,-0.060888,0.995433,1.209221,1.089852,-1.026698
1,-0.158385,0.661504,-0.915755,0.479107,-0.833861,2.387330,-1.004049,0.254953,1.403928,1.727137,-2.243675,-0.731971,1.089852,-1.026698
2,1.716520,0.661504,-0.915755,0.764688,-1.396233,-0.418878,0.891255,-1.050593,1.403928,1.301417,-2.243675,-0.731971,1.089852,-1.026698
3,0.723923,0.661504,-0.915755,0.936037,-0.833861,-0.418878,0.891255,0.516062,-0.712287,-0.912329,0.995433,0.238625,1.089852,-1.026698
4,0.834212,-1.511706,-0.915755,0.364875,0.930822,2.387330,0.891255,-1.877438,-0.712287,0.705408,-0.624121,2.179817,-0.522122,-1.026698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,0.503346,0.661504,0.055931,0.479107,-0.484803,-0.418878,0.891255,0.646617,1.403928,-0.912329,0.995433,-0.731971,-0.522122,0.973997
1021,0.613635,0.661504,-0.915755,-0.377636,0.232705,-0.418878,-1.004049,-0.354302,1.403928,1.471705,-0.624121,0.238625,1.089852,-1.026698
1022,-0.820116,0.661504,-0.915755,-1.234378,0.562371,-0.418878,-1.004049,-1.355220,1.403928,-0.060888,-0.624121,0.238625,-0.522122,-1.026698
1023,-0.489251,-1.511706,-0.915755,-1.234378,0.155137,-0.418878,-1.004049,0.429026,-0.712287,-0.912329,0.995433,-0.731971,-0.522122,0.973997
1024,-0.048097,0.661504,-0.915755,-0.663216,-1.124743,-0.418878,0.891255,-1.572811,-0.712287,0.279688,-0.624121,0.238625,1.089852,-1.026698

In [13]:
st.norm.interval(alpha=0.95,loc=np.mean(cardio["chol"]),scale=st.sem(cardio["chol"]))

(242.8415586477306, 249.1584413522694)

In [21]:
#st.norm.interval(alpha=0.95,loc=250,scale=10)

(230.40036015459947, 269.59963984540053)

In [14]:
st.norm.interval(alpha=0.95,loc=np.mean(cardio["trestbps"]),scale=st.sem(cardio["trestbps"]))

(130.5393515374625, 132.68406309668387)

In [15]:
st.norm.interval(alpha=0.99,loc=np.mean(cardio["chol"]),scale=st.sem(cardio["chol"]))

(241.8491044463629, 250.1508955536371)

In [ ]:
# using t score calculating the CI

In [17]:
data5=[12,12,13,13,15,16,17,22,23,25,26,27,28,28,29]

In [19]:
st.t.interval(alpha=0.95,df=len(data5)-1,loc=np.mean(data5),scale=st.sem(data5))

(16.75776979778498, 24.042230202215016)

In [20]:
len(data5)

15